// <auto-generated />
using System;
using LivrariaHBSIS.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LivrariaHBSIS.Infra.Data.Migrations
{
    [DbContext(typeof(ContextoAplicacao))]
    partial class ContextoAplicacaoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LivrariaHBSIS.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new { CategoriaId = 1, Descricao = "Aventura" },
                        new { CategoriaId = 2, Descricao = "Romance Nacional" },
                        new { CategoriaId = 3, Descricao = "Romance Estrangeiro" },
                        new { CategoriaId = 4, Descricao = "Terror" },
                        new { CategoriaId = 5, Descricao = "Biografia" },
                        new { CategoriaId = 6, Descricao = "Autobiografia" },
                        new { CategoriaId = 7, Descricao = "Autoajuda" },
                        new { CategoriaId = 8, Descricao = "Religião" }
                    );
                });

            modelBuilder.Entity("LivrariaHBSIS.Domain.Entities.Livro", b =>
                {
                    b.Property<int>("LivroId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoLancamento");

                    b.Property<int>("CategoriaId");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<byte>("Edicao");

                    b.Property<string>("Editora")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("ISBN");

                    b.Property<string>("NomeAutor")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NomeLivro")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("LivroId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Livro");
                });

            modelBuilder.Entity("LivrariaHBSIS.Domain.Entities.Livro", b =>
                {
                    b.HasOne("LivrariaHBSIS.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Livros")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
